// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: randomNumber.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pb;

@kotlin.jvm.JvmName("-initializerandomRangeRequest")
public inline fun randomRangeRequest(block: pb.RandomRangeRequestKt.Dsl.() -> kotlin.Unit): pb.RandomRangeRequest =
  pb.RandomRangeRequestKt.Dsl._create(pb.RandomRangeRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pb.RandomRangeRequest`
 */
public object RandomRangeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pb.RandomRangeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pb.RandomRangeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pb.RandomRangeRequest = _builder.build()

    /**
     * `int32 rangeI = 1;`
     */
    public var rangeI: kotlin.Int
      @JvmName("getRangeI")
      get() = _builder.getRangeI()
      @JvmName("setRangeI")
      set(value) {
        _builder.setRangeI(value)
      }
    /**
     * `int32 rangeI = 1;`
     */
    public fun clearRangeI() {
      _builder.clearRangeI()
    }

    /**
     * `int32 rangeL = 2;`
     */
    public var rangeL: kotlin.Int
      @JvmName("getRangeL")
      get() = _builder.getRangeL()
      @JvmName("setRangeL")
      set(value) {
        _builder.setRangeL(value)
      }
    /**
     * `int32 rangeL = 2;`
     */
    public fun clearRangeL() {
      _builder.clearRangeL()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun pb.RandomRangeRequest.copy(block: pb.RandomRangeRequestKt.Dsl.() -> kotlin.Unit): pb.RandomRangeRequest =
  pb.RandomRangeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

