// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomNumber.proto

package pb;

public interface RandomNumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.RandomNumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rNumber = 1;</code>
   * @return The rNumber.
   */
  int getRNumber();
}
