// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomNumber.proto

package pb;

public interface RandomRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.RandomRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rangeI = 1;</code>
   * @return The rangeI.
   */
  int getRangeI();

  /**
   * <code>int32 rangeL = 2;</code>
   * @return The rangeL.
   */
  int getRangeL();
}
