// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomNumber.proto

package pb;

/**
 * Protobuf type {@code pb.RandomRangeRequest}
 */
public final class RandomRangeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.RandomRangeRequest)
    RandomRangeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RandomRangeRequest.newBuilder() to construct.
  private RandomRangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RandomRangeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RandomRangeRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pb.RandomNumber.internal_static_pb_RandomRangeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pb.RandomNumber.internal_static_pb_RandomRangeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pb.RandomRangeRequest.class, pb.RandomRangeRequest.Builder.class);
  }

  public static final int RANGEI_FIELD_NUMBER = 1;
  private int rangeI_ = 0;
  /**
   * <code>int32 rangeI = 1;</code>
   * @return The rangeI.
   */
  @java.lang.Override
  public int getRangeI() {
    return rangeI_;
  }

  public static final int RANGEL_FIELD_NUMBER = 2;
  private int rangeL_ = 0;
  /**
   * <code>int32 rangeL = 2;</code>
   * @return The rangeL.
   */
  @java.lang.Override
  public int getRangeL() {
    return rangeL_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rangeI_ != 0) {
      output.writeInt32(1, rangeI_);
    }
    if (rangeL_ != 0) {
      output.writeInt32(2, rangeL_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rangeI_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rangeI_);
    }
    if (rangeL_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, rangeL_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pb.RandomRangeRequest)) {
      return super.equals(obj);
    }
    pb.RandomRangeRequest other = (pb.RandomRangeRequest) obj;

    if (getRangeI()
        != other.getRangeI()) return false;
    if (getRangeL()
        != other.getRangeL()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RANGEI_FIELD_NUMBER;
    hash = (53 * hash) + getRangeI();
    hash = (37 * hash) + RANGEL_FIELD_NUMBER;
    hash = (53 * hash) + getRangeL();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pb.RandomRangeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb.RandomRangeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb.RandomRangeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb.RandomRangeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb.RandomRangeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pb.RandomRangeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pb.RandomRangeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb.RandomRangeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb.RandomRangeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pb.RandomRangeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pb.RandomRangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pb.RandomRangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pb.RandomRangeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.RandomRangeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.RandomRangeRequest)
      pb.RandomRangeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.RandomNumber.internal_static_pb_RandomRangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.RandomNumber.internal_static_pb_RandomRangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.RandomRangeRequest.class, pb.RandomRangeRequest.Builder.class);
    }

    // Construct using pb.RandomRangeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rangeI_ = 0;
      rangeL_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pb.RandomNumber.internal_static_pb_RandomRangeRequest_descriptor;
    }

    @java.lang.Override
    public pb.RandomRangeRequest getDefaultInstanceForType() {
      return pb.RandomRangeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public pb.RandomRangeRequest build() {
      pb.RandomRangeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pb.RandomRangeRequest buildPartial() {
      pb.RandomRangeRequest result = new pb.RandomRangeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(pb.RandomRangeRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rangeI_ = rangeI_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rangeL_ = rangeL_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pb.RandomRangeRequest) {
        return mergeFrom((pb.RandomRangeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pb.RandomRangeRequest other) {
      if (other == pb.RandomRangeRequest.getDefaultInstance()) return this;
      if (other.getRangeI() != 0) {
        setRangeI(other.getRangeI());
      }
      if (other.getRangeL() != 0) {
        setRangeL(other.getRangeL());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rangeI_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              rangeL_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int rangeI_ ;
    /**
     * <code>int32 rangeI = 1;</code>
     * @return The rangeI.
     */
    @java.lang.Override
    public int getRangeI() {
      return rangeI_;
    }
    /**
     * <code>int32 rangeI = 1;</code>
     * @param value The rangeI to set.
     * @return This builder for chaining.
     */
    public Builder setRangeI(int value) {

      rangeI_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rangeI = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRangeI() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rangeI_ = 0;
      onChanged();
      return this;
    }

    private int rangeL_ ;
    /**
     * <code>int32 rangeL = 2;</code>
     * @return The rangeL.
     */
    @java.lang.Override
    public int getRangeL() {
      return rangeL_;
    }
    /**
     * <code>int32 rangeL = 2;</code>
     * @param value The rangeL to set.
     * @return This builder for chaining.
     */
    public Builder setRangeL(int value) {

      rangeL_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rangeL = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRangeL() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rangeL_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.RandomRangeRequest)
  }

  // @@protoc_insertion_point(class_scope:pb.RandomRangeRequest)
  private static final pb.RandomRangeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pb.RandomRangeRequest();
  }

  public static pb.RandomRangeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RandomRangeRequest>
      PARSER = new com.google.protobuf.AbstractParser<RandomRangeRequest>() {
    @java.lang.Override
    public RandomRangeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RandomRangeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RandomRangeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pb.RandomRangeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

